### ISSUE TITLE
Function all() breaks everything

### ISSUE THREAD

**Issue by pjl4** [codingdojo-mean-0219/plutz#2]
without the all() function next 10 and previous 10 work.

with the all() function clicking on either planets or people forces into an unending loop of getting next 10 until it is undefined

**Comment by pjl4** [comment]
fixed and completed

**Comment by dojo-json** [comment]
Hey, just noticed this issue. Remember if you need assistance you can assign the issue to me and I will get a notification. Otherwise I may not see it right away.
